2025-09-20 18:13:50,419 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:13:50,419 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:13:50,423 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:13:50,423 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:13:50,424 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:13:50,424 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:13:50,424 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:13:50,424 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:13:50,425 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:13:50,425 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:13:50,425 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:13:50,425 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:40:45,751 - models.ai_models - INFO - ai_models.py:349 - Cleaning up model manager resources...
2025-09-20 18:40:45,751 - models.ai_models - INFO - ai_models.py:349 - Cleaning up model manager resources...
2025-09-20 18:40:45,752 - models.ai_models - INFO - ai_models.py:359 - Model manager cleanup completed
2025-09-20 18:40:45,752 - models.ai_models - INFO - ai_models.py:359 - Model manager cleanup completed
2025-09-20 18:40:58,639 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:40:58,639 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:40:58,640 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:40:58,640 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:40:58,640 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:40:58,640 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:40:58,640 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:40:58,640 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:40:58,642 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:40:58,642 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:40:58,643 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:40:58,643 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:41:34,294 - models.ai_models - INFO - ai_models.py:349 - Cleaning up model manager resources...
2025-09-20 18:41:34,294 - models.ai_models - INFO - ai_models.py:349 - Cleaning up model manager resources...
2025-09-20 18:41:34,295 - models.ai_models - INFO - ai_models.py:359 - Model manager cleanup completed
2025-09-20 18:41:34,295 - models.ai_models - INFO - ai_models.py:359 - Model manager cleanup completed
2025-09-20 18:41:48,855 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:41:48,855 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:41:48,857 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:41:48,857 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:41:48,858 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:41:48,858 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:41:48,859 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:41:48,859 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:41:48,859 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:41:48,859 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:41:48,860 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:41:48,860 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:44:35,642 - models.ai_models - INFO - ai_models.py:349 - Cleaning up model manager resources...
2025-09-20 18:44:35,642 - models.ai_models - INFO - ai_models.py:349 - Cleaning up model manager resources...
2025-09-20 18:44:35,643 - models.ai_models - INFO - ai_models.py:359 - Model manager cleanup completed
2025-09-20 18:44:35,643 - models.ai_models - INFO - ai_models.py:359 - Model manager cleanup completed
2025-09-20 18:44:52,708 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:44:52,708 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:44:52,709 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:44:52,709 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:44:52,710 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:44:52,710 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:44:52,711 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:44:52,711 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:44:52,711 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:44:52,711 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:44:52,712 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:44:52,712 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:45:04,741 - models.ai_models - INFO - ai_models.py:350 - Cleaning up model manager resources...
2025-09-20 18:45:04,741 - models.ai_models - INFO - ai_models.py:350 - Cleaning up model manager resources...
2025-09-20 18:45:04,745 - models.ai_models - INFO - ai_models.py:360 - Model manager cleanup completed
2025-09-20 18:45:04,745 - models.ai_models - INFO - ai_models.py:360 - Model manager cleanup completed
2025-09-20 18:45:17,000 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:45:17,000 - models.ai_models - INFO - ai_models.py:37 - Loading AI models...
2025-09-20 18:45:17,002 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:45:17,002 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:45:17,004 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:45:17,004 - models.ai_models - WARNING - ai_models.py:63 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:45:17,004 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:45:17,004 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:45:17,005 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:45:17,005 - models.ai_models - WARNING - ai_models.py:69 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:45:17,005 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:45:17,005 - models.ai_models - INFO - ai_models.py:89 - Model loading completed
2025-09-20 18:46:22,405 - models.ai_models - INFO - ai_models.py:359 - Cleaning up model manager resources...
2025-09-20 18:46:22,405 - models.ai_models - INFO - ai_models.py:359 - Cleaning up model manager resources...
2025-09-20 18:46:22,406 - models.ai_models - INFO - ai_models.py:369 - Model manager cleanup completed
2025-09-20 18:46:22,406 - models.ai_models - INFO - ai_models.py:369 - Model manager cleanup completed
2025-09-20 18:46:53,959 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 18:46:53,959 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 18:46:53,964 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:46:53,964 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:46:53,967 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:46:53,967 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:46:53,968 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:46:53,968 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:46:53,972 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:46:53,972 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:46:53,975 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 18:46:53,975 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 18:46:54,710 - models.ai_models - INFO - ai_models.py:360 - Cleaning up model manager resources...
2025-09-20 18:46:54,710 - models.ai_models - INFO - ai_models.py:360 - Cleaning up model manager resources...
2025-09-20 18:46:54,710 - models.ai_models - INFO - ai_models.py:370 - Model manager cleanup completed
2025-09-20 18:46:54,710 - models.ai_models - INFO - ai_models.py:370 - Model manager cleanup completed
2025-09-20 18:47:31,506 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 18:47:31,506 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 18:47:31,509 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:47:31,509 - models.lstm_health_model - ERROR - lstm_health_model.py:302 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:47:31,510 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:47:31,510 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:47:31,511 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:47:31,511 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 18:47:31,512 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:47:31,512 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 18:47:31,513 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 18:47:31,513 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 18:51:59,360 - models.ai_models - INFO - ai_models.py:361 - Cleaning up model manager resources...
2025-09-20 18:51:59,360 - models.ai_models - INFO - ai_models.py:361 - Cleaning up model manager resources...
2025-09-20 18:51:59,360 - models.ai_models - INFO - ai_models.py:371 - Model manager cleanup completed
2025-09-20 18:51:59,360 - models.ai_models - INFO - ai_models.py:371 - Model manager cleanup completed
2025-09-20 20:09:59,912 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:09:59,912 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:09:59,914 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:09:59,914 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:09:59,915 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:09:59,915 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:09:59,916 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:09:59,916 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:09:59,917 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:09:59,917 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:09:59,917 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:09:59,917 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:11:45,356 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 20:11:45,356 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 20:11:45,357 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 20:11:45,357 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 20:11:54,028 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:11:54,028 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:11:54,029 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:11:54,029 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:11:54,029 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:11:54,029 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:11:54,030 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:11:54,030 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:11:54,031 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:11:54,031 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:11:54,031 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:11:54,031 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:12:21,142 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 20:12:21,142 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 20:12:21,142 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 20:12:21,142 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 20:12:29,487 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:12:29,487 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:12:29,489 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:29,489 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:29,489 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:29,489 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:29,490 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:29,490 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:29,490 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:29,490 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:29,490 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:12:29,490 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:12:48,741 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 20:12:48,741 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 20:12:48,762 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 20:12:48,762 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 20:12:59,674 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:12:59,674 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:12:59,676 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:59,676 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:59,678 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:59,678 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:59,679 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:59,679 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:12:59,679 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:59,679 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:12:59,680 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:12:59,680 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:59:30,143 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:59:30,143 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 20:59:30,147 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:59:30,147 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:59:30,148 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:59:30,148 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:59:30,149 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:59:30,149 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 20:59:30,150 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:59:30,150 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 20:59:30,151 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 20:59:30,151 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 21:22:49,578 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 21:22:49,578 - models.ai_models - INFO - ai_models.py:365 - Cleaning up model manager resources...
2025-09-20 21:22:49,579 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 21:22:49,579 - models.ai_models - INFO - ai_models.py:375 - Model manager cleanup completed
2025-09-20 21:25:20,560 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 21:25:20,560 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-20 21:25:20,561 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 21:25:20,561 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 21:25:20,562 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 21:25:20,562 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 21:25:20,562 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 21:25:20,562 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-20 21:25:20,563 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 21:25:20,563 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-20 21:25:20,563 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-20 21:25:20,563 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-25 03:05:45,158 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-25 03:05:45,158 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-25 03:05:45,162 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:05:45,162 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:05:45,162 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:05:45,162 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:05:45,163 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:05:45,163 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:05:45,164 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:05:45,164 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:05:45,165 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-25 03:05:45,165 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-25 03:07:13,621 - models.ai_models - INFO - ai_models.py:369 - Cleaning up model manager resources...
2025-09-25 03:07:13,621 - models.ai_models - INFO - ai_models.py:369 - Cleaning up model manager resources...
2025-09-25 03:07:13,624 - models.ai_models - INFO - ai_models.py:379 - Model manager cleanup completed
2025-09-25 03:07:13,624 - models.ai_models - INFO - ai_models.py:379 - Model manager cleanup completed
2025-09-25 03:07:35,763 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-25 03:07:35,763 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-25 03:07:35,771 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:07:35,771 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:07:35,771 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:07:35,771 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:07:35,773 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:07:35,773 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:07:35,774 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:07:35,774 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:07:35,775 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-25 03:07:35,775 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-25 03:08:16,805 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-25 03:08:16,806 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:08:16,807 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:08:16,807 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:08:16,807 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:08:16,809 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-25 03:08:16,812 - models.ai_models - INFO - ai_models.py:369 - Cleaning up model manager resources...
2025-09-25 03:08:16,812 - models.ai_models - INFO - ai_models.py:379 - Model manager cleanup completed
2025-09-25 03:09:24,231 - models.ai_models - INFO - ai_models.py:369 - Cleaning up model manager resources...
2025-09-25 03:09:24,231 - models.ai_models - INFO - ai_models.py:369 - Cleaning up model manager resources...
2025-09-25 03:09:24,232 - models.ai_models - INFO - ai_models.py:379 - Model manager cleanup completed
2025-09-25 03:09:24,232 - models.ai_models - INFO - ai_models.py:379 - Model manager cleanup completed
2025-09-25 03:09:45,010 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-25 03:09:45,010 - models.ai_models - INFO - ai_models.py:38 - Loading AI models...
2025-09-25 03:09:45,014 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:09:45,014 - models.lstm_health_model - ERROR - lstm_health_model.py:338 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:09:45,015 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:09:45,015 - models.ai_models - WARNING - ai_models.py:64 - Could not load LSTM model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/lstm_health_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:09:45,016 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:09:45,016 - models.transformer_genomic_model - ERROR - transformer_genomic_model.py:418 - Error loading model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2025-09-25 03:09:45,019 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:09:45,019 - models.ai_models - WARNING - ai_models.py:70 - Could not load Transformer model: [Errno 2] Unable to synchronously open file (unable to open file: name = './models/transformer_genomic_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Will need training.
2025-09-25 03:09:45,020 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
2025-09-25 03:09:45,020 - models.ai_models - INFO - ai_models.py:90 - Model loading completed
